### ISSUE TITLE
Create fixed navbar

### ISSUE THREAD

**Issue by saksham-kapoor** [dsc-nsut/dsc-nsut.github.io#1]
## Create a fully responsive sticky navbar
Should contain the following links -
1. Home
2. Events
3. Our Team
4. Feed
5. Contact Us

**Comment by adnanhashmi09** [comment]
Hii,
I would like to work on creating the navbar. I have forked the repo.

**Comment by saumyasingh203** [comment]
@adnanhashmi09 
Great! Please follow the guidelines mentioned in the Readme.md file :)
