### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by saksham-kapoor** [dsc-nsut/dsc-nsut.github.io#5]
Create team page with the following sections -
1. Core Team
2. Web Team
3. Android Team
4. ML Team
5. Competitive Programming Team 
6. Graphics Team
7. Content Team

### 5 column layout with circular images, name and designation

refer -> https://dscvit.com/team.html

**Comment by iShubhamRana** [comment]
I would like to work on this :)

**Comment by saumyasingh203** [comment]
Sure @iShubhamRana 
Make sure you follow the guidelines mentioned in the Readme.md file :)

**Comment by iShubhamRana** [comment]
![page1](https://user-images.githubusercontent.com/77272322/118449868-3404f800-b711-11eb-9307-a18dd85671fd.PNG)
![page2](https://user-images.githubusercontent.com/77272322/118449873-36675200-b711-11eb-807b-2ff1307f53c7.PNG)
![page3](https://user-images.githubusercontent.com/77272322/118449876-37987f00-b711-11eb-9a58-8d5bac068496.PNG)
