### ISSUE TITLE
Feed Page

### ISSUE THREAD

**Issue by saksham-kapoor** [dsc-nsut/dsc-nsut.github.io#6]
## Create Feed Page
1. Show all Instagram posters in 3 column layout
2. Add buttons/links to each image linking to the original post

**Comment by weirdrag08** [comment]
Please assign me this issue ;-)

**Comment by saumyasingh203** [comment]
Sure! @weirdrag08

**Comment by weirdrag08** [comment]
@saumyasingh203 . I wanted to confirm two things regarding this issue beforehand, if you could please enlighten me with it. 
1) As told in point 1 we have to show all the instagram posters in feedpage, so does that include the posters related to festivals(like holi one) and the screenshots of meeting link or do we just have to include the technical ones and those related to events?

2) As asked , we have to make the 3 column layout but for small viewports according to my suggestion it would get a little messy. So do we have to follow 3 col itself for small viewports or we can go for 1 or 2 col layouts?

Thankyou ;)

**Comment by saumyasingh203** [comment]
@weirdrag08 
Great that you addressed these doubts before hand ✔️ 

1. Choose the relevant and technical ones only for now
2. Yes totally, the website should be fully responsive in all aspects, it should reduce 3 -> 2 -> 1 column layout dynamically when the size of the window is reduced

**Comment by saumyasingh203** [comment]
@weirdrag08 
Make sure you git pull recent changes in the repository, the index.html file has been shifted to the root folder and the necessary changes have been incorporated in the current version. Rest of the HTML files except index.html will be placed inside the Layouts folder like before.

Write the rest of the code accordingly!

**Comment by weirdrag08** [comment]
Will sure keep that in mind

**Comment by weirdrag08** [comment]
> @weirdrag08
> Make sure you git pull recent changes in the repository, the index.html file has been shifted to the root folder and the necessary changes have been incorporated in the current version. Rest of the HTML files except index.html will be placed inside the Layouts folder like before.
> 
> Write the rest of the code accordingly!

Will sure keep that in mind

**Comment by saumyasingh203** [comment]
Superb work @weirdrag08 💯
