### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by saksham-kapoor** [dsc-nsut/dsc-nsut.github.io#7]
## Tasks

1. Add all social media links
2. Create a simple copyright block.

**Comment by weirdrag08** [comment]
Please assign me this issue .

**Comment by saumyasingh203** [comment]
@weirdrag08 
You can start working on the issue now :)
Make sure you follow the guidelines mentioned in the Readme.md file

**Comment by weirdrag08** [comment]
Completed issue :)
